spring.application.name=monitor-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/monitor_db?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.kafka.bootstrap-servers=localhost:29092,localhost:39092,localhost:49092
spring.jpa.hibernate.ddl-auto=update
server.port=8082
logging.level.org.springframework.kafka=INFO
